language: r
r:
  - release
    #- devel

dist: xenial
os: linux

branches:
  only:
  - master
  - develop

addons:
  apt:
    packages:
      - vim
      - ruby
      - python-matplotlib
      #      - r-base 
      #      - r-base-dev

install:
  # Install vim plugins
  - curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - cp .travis/vimrc ~/.vimrc
  - vim -u ~/.vimrc +PlugInstall +qall
 
before_script:
  - mkdir -p ~/R/library
  - export R_LIBS_USER="~/R/library/"

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
    - $R_LIBS_USER
  packages: true

script:
  - vim --version
  - python --version
  - perl --version
  - ruby --version
  - R --version
  - python ./vim-plugins-profile.py vim -u NONE
  - python ./vim-plugins-profile.py vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -n 5 vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -n 5 -r 10 vim -u .travis/vimrc
  - python ./vim-plugins-profile.py -s vim -N -u NORC
  - perl ./vim-plugins-profile.pl
  - ruby ./vim-plugins-profile.rb
  - yes | bash vim-plugins-profile.sh
  #- find ~/R/
  #- ls -laR ~/R/
